server:
  port: 9200

eureka:
  client:
    service-url:
      # 集群版本
      #      defaultZone: http://admin:admin@localhost:8761/eureka,http://admin:admin@localhost:8762/eureka
      # 单机版本
      defaultZone: http://admin:admin@localhost:8761/eureka

spring:
  application:
    name: SEARCH
